version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - "/"
      - "/actions/*"
    schedule:
      interval: 'weekly'
    groups:
      setup-java:
        patterns:
          - "actions/setup-java"
      checkout:
        patterns:
          - "actions/checkout"
