version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - "/"
      - "/actions/*"
    schedule:
      interval: 'weekly'
    groups:
      actions/checkout: { patterns: ["actions/checkout"] }
      actions/setup-java: { patterns: [ "actions/setup-java" ] }
      actions/upload-artifact: { patterns: [ "actions/upload-artifact" ] }
      actions/download-artifact: { patterns: [ "actions/download-artifact" ] }
      actions/create-github-app-token: { patterns: [ "actions/create-github-app-token" ] }
      sbt/setup-sbt: { patterns: ["sbt/setup-sbt"] }
    cooldown:
      default-days: 7
