version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - "/"
      - "/actions/*"
    schedule:
      interval: 'weekly'
    groups:
      actions/setup-java: { patterns: ["actions/setup-java"] }
      actions/checkout: { patterns: ["actions/checkout"] }
      actions/upload-artifact: { patterns: [ "actions/upload-artifact" ] }
      sbt/setup-sbt: { patterns: ["sbt/setup-sbt"] }
    cooldown:
      default-days: 7
